language: java
matrix:
  include:
    - jdk: openjdk8
      # This is the primary target platform. In this build we perform a
      # SonarQube analysis.
      script:
        - ./mvnw install sonar:sonar
        #- ./build-dependents.sh "${HOME}/.dependants"
        - bundle exec danger
        - find . -name "*.sh" -print0 | xargs -0 shellcheck
    - jdk: openjdk11
      script:
        - ./mvnw install sonar:sonar
        #- ./build-dependents.sh "${HOME}/.dependants"
addons:
  apt:
    packages:
      - xmlstarlet
  bundler: true
  sonarcloud:
    organization: picnic-technologies
    token: "${SONARCLOUD_TOKEN}"
install:
  - mvn io.takari:maven:wrapper
  - bundle install
before_cache:
  # Don't cache the artifacts we just generated, for multiple reasons: (1) we
  # shouldn't need them next time around and (2) if we do, that indicates a
  # dependency issue which might otherwise go unnoticed until next time we bump
  # the project's version (i.e., when tagging).
  - find "${HOME}/.m2/repository" -depth -name '*-SNAPSHOT' -exec rm -r '{}' \;
cache:
  directories:
    # The directory in which `build-dependents.sh` clones and builds projects
    # that depend on this project.
    - ${HOME}/.dependants
    # The local Maven repository in which third party dependencies are stored.
    - ${HOME}/.m2/repository
    # The Takari Maven Wrapper's storage for downloaded Maven distributions.
    - ${HOME}/.m2/wrapper
    # The SonarQube analysis cache.
    - ${HOME}/.sonar/cache
